'use server';

/**
 * @fileOverview This file defines the Genkit flow for generating visual memory prompts
 * based on session themes and emotional content.
 */

import { z } from 'genkit';

import { ai } from '@/ai/genkit';
import { sanitizeInput, sanitizeArray, validateSpicyLevel } from './shared-utils';

const VisualMemoryInputSchema = z.object({
  summary: z.string().describe('The session summary generated by the Scribe.'),
  spicyLevel: z.string().describe('The spicy level of the session (Mild, Medium, Hot, Extra-Hot).'),
  sharedThemes: z
    .array(z.string())
    .describe('Array of shared themes/topics identified in the session.'),
});

export type VisualMemoryInput = z.infer<typeof VisualMemoryInputSchema>;

const VisualMemoryOutputSchema = z.object({
  imagePrompt: z
    .string()
    .describe(
      'An artistic, abstract image description suitable for AI image generation. Should be metaphorical and tasteful.'
    ),
  safetyLevel: z
    .enum(['safe', 'moderate', 'explicit'])
    .describe('Content safety level of the suggested image.'),
});

export type VisualMemoryOutput = z.infer<typeof VisualMemoryOutputSchema>;

export async function generateVisualMemory(input: VisualMemoryInput): Promise<VisualMemoryOutput> {
  // Validate and sanitize inputs to prevent prompt injection
  const sanitizedInput = {
    summary: sanitizeInput(input.summary, 2000),
    spicyLevel: validateSpicyLevel(input.spicyLevel),
    sharedThemes: sanitizeArray(input.sharedThemes, 200),
  };

  return visualMemoryFlow(sanitizedInput);
}

const prompt = ai.definePrompt({
  name: 'visualMemoryPrompt',
  input: { schema: VisualMemoryInputSchema },
  output: { schema: VisualMemoryOutputSchema },
  prompt: `You are an artistic director specializing in creating abstract, metaphorical visual representations of intimate conversations. Your task is to transform the emotional themes of a conversation into a tasteful, artistic image prompt.

Session Context:
-   Summary: {{summary}}
-   Spicy Level: {{spicyLevel}}
-   Shared Themes: {{#each sharedThemes}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}

Your Guidelines:
1. **Be Abstract and Metaphorical**: Use artistic metaphors, not literal representations
2. **Avoid Explicit Content**: Never suggest nudity, explicit acts, or graphic content
3. **Use Artistic Language**: Reference art styles, lighting, color palettes, textures
4. **Focus on Emotion**: Capture the emotional tone through visual symbolism
5. **Keep it Tasteful**: Even for "Hot" or "Extra-Hot" sessions, use sophisticated metaphors

Style Examples by Spicy Level:
- **Mild**: "Watercolor painting of intertwined light trails in soft pastels, gentle curves flowing together"
- **Medium**: "Abstract oil painting of two flames dancing together, warm oranges and deep reds, impressionist style"
- **Hot**: "Abstract sculpture concept: fire and silk merging, dramatic lighting, contemporary art style"
- **Extra-Hot**: "Bold abstract expressionist painting with intense reds and blacks, swirling energy, passion depicted through color and movement"

Image Prompt Structure:
Start with the art medium/style, then describe the abstract subject, add details about color palette, lighting, and mood. Keep it between 50-100 words.

Safety Levels:
- **safe**: Suitable for all audiences, gentle themes
- **moderate**: Artistic but suggests intimacy through metaphor
- **explicit**: Should NEVER be used - we always use metaphor

Now generate an artistic image prompt based on the provided session context.
`,
});

const visualMemoryFlow = ai.defineFlow(
  {
    name: 'visualMemoryFlow',
    inputSchema: VisualMemoryInputSchema,
    outputSchema: VisualMemoryOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    return output!;
  }
);
