name: whispers-and-flames
region: nyc
databases:
  - name: whispers-flames-db
    engine: PG
    production: true
features:
  - buildpack-stack=ubuntu-22
services:
  - name: web
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    github:
      repo: Phazzie/WhispersAndFlames
      branch: main
      deploy_on_push: true
    build_command: npm run build
    run_command: npm start
    http_port: 3000
    health_check:
      http_path: /api/health
      initial_delay_seconds: 20
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${whispers-flames-db.DATABASE_URL}
      - key: XAI_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: GEMINI_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: NEXT_PUBLIC_APP_URL
        scope: RUN_AND_BUILD_TIME
        value: ${APP_URL}
